name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      KOSLI_API_TOKEN: ${{ secrets.MY_KOSLI_API_TOKEN }}
      KOSLI_OWNER: KojotMaciek

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: setup kosli
      uses: kosli-dev/setup-cli-action@v1
    - name: declare pipeline
      run: kosli pipeline declare --pipeline docker-hello -t pull-request,artifact

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}    
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: chapter02
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello:${{ steps.vars.outputs.sha_short }}

    - name: Verify image
      run: docker image ls
